[package]
name = "horsemint"
version = "0.1.0"
authors = ["Danny Sauer <danny@dannysauer.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#mqtt = "0.1.4"
rumqttc = "0.0.6"
config = "0.10.1"
